#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : thunar-volman
Version  : 0.8.1
Release  : 4
URL      : http://archive.xfce.org/src/xfce/thunar-volman/0.8/thunar-volman-0.8.1.tar.bz2
Source0  : http://archive.xfce.org/src/xfce/thunar-volman/0.8/thunar-volman-0.8.1.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: thunar-volman-bin
Requires: thunar-volman-data
Requires: thunar-volman-locales
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(exo-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(libxfce4ui-1)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)

%description
What is it?
===========
thunar-volman is an extension for the Thunar File Manager, which enables
automatic management of removable drives and media. For example, if
thunar-volman is installed and configured properly, and you plug in your
digitcal camera, it will automatically spawn your preferred photo application
and import the new pictures from your camera.

%package bin
Summary: bin components for the thunar-volman package.
Group: Binaries
Requires: thunar-volman-data

%description bin
bin components for the thunar-volman package.


%package data
Summary: data components for the thunar-volman package.
Group: Data

%description data
data components for the thunar-volman package.


%package locales
Summary: locales components for the thunar-volman package.
Group: Default

%description locales
locales components for the thunar-volman package.


%prep
%setup -q -n thunar-volman-0.8.1

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang thunar-volman

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/thunar-volman
/usr/bin/thunar-volman-settings

%files data
%defattr(-,root,root,-)
/usr/share/applications/thunar-volman-settings.desktop
/usr/share/icons/hicolor/48x48/apps/tvm-burn-cd.png
/usr/share/icons/hicolor/48x48/apps/tvm-dev-pocketpc.png
/usr/share/icons/hicolor/scalable/apps/tvm-burn-cd.svg

%files locales -f thunar-volman.lang 
%defattr(-,root,root,-)

